name: NuGet
on:
  workflow_dispatch:

defaults:
    run:
        shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # Install the .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Create the NuGet package
    - run: dotnet pack --configuration Release --output bin

    # Publish the NuGet package as an artifact, so they can be used in the following jobs
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: bin/*.nupkg
        
  publish:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      # Download the NuGet package created in the previous job
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: bin

      # Install the .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      # Publish all NuGet packages to NuGet.org
      - name: Publish NuGet package
        run: |
          foreach ($file in (Get-ChildItem bin -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_API }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }